[package]
name = "csqrl/find-up"
description = "Find an Instance by walking up ancestors"
version = "1.0.0"
license = "MIT"
authors = ["csqrl (https://csqrl.dev)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dev-dependencies]
TestEZ = "roblox/testez@^0.4.1"
Roact = "roblox/roact@^1.4.3"
